[package]
name = "rebuilderd-common"
version = "0.7.0"
description = "rebuilderd - common code"
authors = ["kpcyrd <git@rxv.cc>"]
license = "GPL-3.0"
repository = "https://github.com/kpcyrd/rebuilderd"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.32"
log = "0.4"
serde = { version="1.0", features=["derive"] }
strum = "0.19"
strum_macros = "0.19"
reqwest = { version="0.10", features=["blocking", "json"] }
chrono = { version = "0.4", features=["serde"] }
colored = "2"
dirs-next = "2"
toml = "0.5.6"
base64-serde = "0.6.1"
base64 = "0.13"
tokio-compat-02 = "0.1.2"
