[package]
name = "rebuilderd-worker"
version = "0.5.0"
description = "rebuilderd - rebuild worker"
authors = ["kpcyrd <git@rxv.cc>"]
license = "GPL-3.0"
repository = "https://github.com/kpcyrd/rebuilderd"
edition = "2018"

[package.metadata.deb]
depends = "$auto, rebuilderd"
assets = [
    ["target/release/rebuilderd-worker", "usr/bin/", "755"],
    ["rebuilder-archlinux.sh", "usr/libexec/rebuilderd/", "755"],
    ["rebuilder-debian.sh", "usr/libexec/rebuilderd/", "755"],
    ["../contrib/confs/rebuilderd-worker.conf", "etc/", "640"],
    ["../contrib/systemd/rebuilderd-worker@.service", "usr/lib/systemd/system/", "640"],
]

[dependencies]
rebuilderd-common = { version="=0.5.0", path="../common" }
structopt = "0.3"
env_logger = "0.8"
sodiumoxide = { version="0.2.5", features=["use-pkg-config"] }
base64 = "0.12"
toml = "0.5.6"
serde = { version="1.0", features=["derive"] }
reqwest = "0.10.4"
tempfile = "3.1.0"
url = "2.1.1"
