name: Binaries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install libsodium-dev libsqlite3-dev

    - name: Build
      run: cargo build --verbose --release

    - name: Strip binary
      run: strip target/release/rebuild{erd,ctl,erd-worker}

    - name: Archive executable (rebuilderd)
      uses: actions/upload-artifact@v1
      with:
        name: rebuilderd
        path: target/release/rebuilderd

    - name: Archive executable (rebuildctl)
      uses: actions/upload-artifact@v1
      with:
        name: rebuildctl
        path: target/release/rebuildctl

    - name: Archive executable (rebuilderd-worker)
      uses: actions/upload-artifact@v1
      with:
        name: rebuilderd-worker
        path: target/release/rebuilderd-worker
